### ISSUE TITLE
panic: A+A=B

### ISSUE THREAD

**Issue by LEXUGE** [LEXUGE/lib-xch-ceb#1]
# Description:
The library will panic when equation is `A+A=B` like.
panic info: 
```
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', /checkout/src/liballoc/vec.rs:1551:10
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

# Other notes:
- `A+A=A+B` `thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 3', /checkout/src/liballoc/vec.rs:1551:10
note: Run with `RUST_BACKTRACE=1` for a backtrace.
`
- `A+A=A+A+B` `thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 5', /checkout/src/liballoc/vec.rs:1551:10
note: Run with `RUST_BACKTRACE=1` for a backtrace.
`

# **HIGH LEVEL**

**Comment by LEXUGE** [comment]
The reason is I just use vector to index the row of the pivots.
my original idea is:
```
col: [1,3,4,5] // the columns of pivots
row: [1,2,3,4] // the row of the pivots
```
But, I access the row by `row[col[foo]]`. This will cause panic because if the `col[foo]` is `5`, it would index `row[5]` which is not indexable.

Now, we are using HashMap to solve this design bug.
